//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_SalePhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colorlist
    {
        public colorlist()
        {
            this.colorproducts = new HashSet<colorproduct>();
        }
    
        public int co_id { get; set; }
        public string co_name { get; set; }
    
        public virtual ICollection<colorproduct> colorproducts { get; set; }
    }
}
