//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_SalePhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagesdetail
    {
        public int img_id { get; set; }
        public int prod_id { get; set; }
        public string img_link { get; set; }
    
        public virtual product product { get; set; }
    }
}
