//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_SalePhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int or_id { get; set; }
        public int cus_id { get; set; }
        public int or_status { get; set; }
        public int cus_total { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
