//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_SalePhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.colorproducts = new HashSet<colorproduct>();
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int prod_id { get; set; }
        public int cate_id { get; set; }
        public string prod_name { get; set; }
        public string prod_icon { get; set; }
        public int prod_price { get; set; }
        public string prod_warranty { get; set; }
        public string prod_accessories { get; set; }
        public string prod_condition { get; set; }
        public string prod_promotion { get; set; }
        public int prod_status { get; set; }
        public string prod_description { get; set; }
        public int prod_featured { get; set; }
        public string prod_screen { get; set; }
        public string prod_os { get; set; }
        public string prod_camf { get; set; }
        public string prod_camr { get; set; }
        public string prod_cpu { get; set; }
        public string prod_ram { get; set; }
        public string prod_Imemory { get; set; }
        public string prod_Ememory { get; set; }
        public string prod_sim { get; set; }
        public string prod_pin { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<colorproduct> colorproducts { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
